add keylog support using SSL_CTX_set_keylog_callback
netty/netty-incubator-codec-quic pull request #343
Opened 2021-10-12 10:09 UTC by lostk1ng

Motivation:

- In order to debug QUIC with tools like Wireshark, we should have access to connection secrets. 
- BoringSSL/OpenSSL provides callback method to log keys. https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_keylog_callback.html

Modifications:

- JNI functions and class BoringSSLKeylogCallback to support keylog callback
- New SSL configuration keylog

Result:

- Now it's possible to log SSL connection secrets with configuration keylog

2021-10-12 11:08 UTC, normanmaurer requested changes

2021-10-12 11:08 UTC, normanmaurer commented on src/main/c/netty_quic_boringssl.c
> +        keyString = (*e)->NewStringUTF(e, line);
you should check if `keyString` is `NULL` after this call which might be the case if we did see an OOME

2021-10-12 11:08 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/BoringSSLKeylogCallback.java
> +    private final InternalLogger logger = InternalLoggerFactory.getInstance(BoringSSLKeylogCallback.class);
```suggestion
    private static final InternalLogger logger = InternalLoggerFactory.getInstance(BoringSSLKeylogCallback.class);
```

2021-10-12 11:08 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/BoringSSLKeylogCallback.java
> +    void logKey(long ssl, String keylog) {
```suggestion
    @SupressWarnings("unused"); 
    void logKey(long ssl, String keylog) {
```

2021-10-13 07:33 UTC, lostk1ng commented on src/main/java/io/netty/incubator/codec/quic/BoringSSLKeylogCallback.java
> +        logger.debug(keylog);
The logging format is [NSS Key Log Format](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format) , following is an sample output，we can log it into a single file and WireShark can directlly use it to do decryption. 

```
CLIENT_HANDSHAKE_TRAFFIC_SECRET 07f0be8cbb8738c52d1dddbabd5e6f04b63790b392d2c5949d20c97ea16851f9 29cb744f34ac6b59316e567963371690f275ecaeac3a4a74d4dd2c1ad7f4a7a3
SERVER_HANDSHAKE_TRAFFIC_SECRET 07f0be8cbb8738c52d1dddbabd5e6f04b63790b392d2c5949d20c97ea16851f9 a4a6af1b6dfb9ae1fec655644bf8ab947f4b4e8950565bb62511dcf262e47bfc
CLIENT_TRAFFIC_SECRET_0 07f0be8cbb8738c52d1dddbabd5e6f04b63790b392d2c5949d20c97ea16851f9 205f727dee8cda1038bf7bf202f97f4bd5e31edfd9f4068930f5acfc7412702e
SERVER_TRAFFIC_SECRET_0 07f0be8cbb8738c52d1dddbabd5e6f04b63790b392d2c5949d20c97ea16851f9 fd829bca10a290ca11ad3c5e5637d6108d00012feeec49ee2756fad7ba47778f
EXPORTER_SECRET 07f0be8cbb8738c52d1dddbabd5e6f04b63790b392d2c5949d20c97ea16851f9 f29d29604358c64b5dcb4cf7757ebd76ffa5d9cbf57855de49ff6603a04b150a
```

2021-10-13 07:39 UTC, normanmaurer commented on src/test/java/io/netty/incubator/codec/quic/TestLogBackAppender.java
> + * Copyright 2020 The Netty Project
```suggestion
 * Copyright 2021 The Netty Project
```

2021-10-13 07:40 UTC, normanmaurer commented on src/test/java/io/netty/incubator/codec/quic/TestLogBackAppender.java
> +    private static final List<String> logs = new ArrayList<>();
Consider using `CopyOnWriteArrayList` as this might be accessed from multiple threads

2021-10-13 07:40 UTC, normanmaurer commented on src/test/java/io/netty/incubator/codec/quic/TestLogBackAppender.java
> +public class TestLogBackAppender extends AppenderBase<ILoggingEvent> {
```suggestion
public final class TestLogBackAppender extends AppenderBase<ILoggingEvent> {
```

2021-10-13 07:41 UTC, normanmaurer commented on src/test/java/io/netty/incubator/codec/quic/QuicChannelConnectTest.java
> +    private void testKeylog(boolean enable) throws Throwable {
```suggestion
    private static void testKeylog(boolean enable) throws Throwable {
```

2021-10-13 08:20 UTC, lostk1ng commented
> > > A few more comments... Also did you sign our ICLA yet ? https://netty.io/s/icla
> > 
> > 
> > no yet. should I register one? BTW, all reviews are fixed.
> 
> Yes you need to sign the ICLA before we can merge this one

I just registered with nickname: lostk1ng

2021-10-13 08:28 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/QuicSslContextBuilder.java
> +     * Enable / disable keylog
Do we also want to document which logger it uses `io.netty.incubator.codec.quic.BoringSSLKeylogCallback` ?

2021-10-13 16:04 UTC, merged