Fix the problem that the test cases QuicWritableTest and QuicReadableTest often fail
netty/netty-incubator-codec-quic pull request #463
Opened 2022-12-18 06:26 UTC by zhining-lu

#458

2023-01-16 15:05 UTC, normanmaurer requested changes

2023-01-19 04:40 UTC, zhining-lu commented on codec-native-quic/src/test/java/io/netty/incubator/codec/quic/QuicWritableTest.java
> +                                Thread.sleep(10);
What's the problem? The sleep time is very short .

2023-01-19 14:22 UTC, normanmaurer commented on codec-native-quic/src/test/java/io/netty/incubator/codec/quic/QuicWritableTest.java
> +                                Thread.sleep(10);
The problem is that it must work without a sleep. This just shows that there is some bug somewhere.

2023-01-23 07:55 UTC, normanmaurer commented
I hope this is fixed now

2023-01-23 07:55 UTC, closed without merging