ChannelOption to identify peer cert server name for quiche::connect
netty/netty-incubator-codec-quic pull request #48
Opened 2020-11-22 08:00 UTC by kachayev

Motivation:

`quiche::connect` function takes an option `server_name` argument for peer's certificate verification. Previously was always set to NULL.

Modifications:

* Defines `QuicChannelConfig` to be used instead of default with additional `QUIC_PEER_CERT_SERVER_NAME` option
* When creating Quiche connection, uses `server_name` set into the config (if any)

Result:

Full coverage for `quiche::connect` arguments, fixes #16

2020-11-22 08:52 UTC, normanmaurer requested changes

2020-11-22 08:52 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/DefaultQuicChannelConfig.java
> +    public DefaultQuicChannelConfig(Channel channel) {
Package private

2020-11-22 08:52 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/DefaultQuicChannelConfig.java
> +    public String getPeerCertServerName() {
Missing override annotation

2020-11-22 08:52 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/DefaultQuicChannelConfig.java
> +    public DefaultQuicChannelConfig setPeerCertServerName(String peerCertServerName) {
Missing override annotation

2020-11-22 08:52 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/QuicChannelConfig.java
> +    ChannelConfig setPeerCertServerName(String peerCertServerName);
Should return QuicChannelConfig , also you should override all the other methods to return it as well

2020-11-22 08:52 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/QuicChannelConfig.java
> +    String getPeerCertServerName();
Javadocs missing for both methods

2020-11-22 08:52 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/QuicChannelConfig.java
> +    ChannelOption<String> QUIC_PEER_CERT_SERVER_NAME = ChannelOption.valueOf("QUIC_PEER_CERT_SERVER_NAME");
Create a QuicChannelOptions class and put it there. Same pattern as we use on epoll etc

2020-11-22 09:34 UTC, kachayev commented
@normanmaurer seems like all covered now!

2020-11-22 12:28 UTC, normanmaurer requested changes

2020-11-22 12:28 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/DefaultQuicChannelConfig.java
> +public class DefaultQuicChannelConfig extends DefaultChannelConfig implements QuicChannelConfig {
Package private and final

2020-11-22 12:28 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/QuicChannelConfig.java
> +public interface QuicChannelConfig extends ChannelConfig {
QuicChannel should now return QuicChannelConfig

2020-11-22 21:14 UTC, kachayev commented
@normanmaurer Fixed both

2020-11-23 07:04 UTC, normanmaurer requested changes

2020-11-23 07:04 UTC, normanmaurer commented on src/main/java/io/netty/incubator/codec/quic/QuicheQuicChannel.java
> +        final String serverName = config().getOption(QuicChannelOption.PEER_CERT_SERVER_NAME);
```suggestion
        final String serverName = config().getPeerCertServerName();
```

2020-11-23 07:24 UTC, merged

2020-11-23 07:24 UTC, normanmaurer commented
@kachayev thanks a lot!

2020-11-23 07:28 UTC, kachayev commented
@normanmaurer Thanks for the last changes! I'm going to work on exposing `keylog_path` setting using the same approach. Will submit a PR in a couple of days.