fix jni_GetByteArrayElements release
netty/netty-incubator-codec-quic pull request #533
Opened 2023-06-10 16:12 UTC by wuhaocn

Caught the memory overflow stack

_malloc_zone_malloc_instrumented_or_legacy libsystem_malloc.dylib
os::malloc(unsigned long, MemoryType, NativeCallStack const&) libjvm.dylib
AllocateHeap(unsigned long, MemoryType, NativeCallStack const&, AllocFailStrategy::AllocFailEnum) libjvm.dylib
jni_GetByteArrayElements libjvm.dylib

2023-06-10 16:15 UTC, normanmaurer requested changes

2023-06-10 16:15 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +        (*env)->DeleteLocalRef(env, bytes);
```suggestion
```

This is not needed.. local ref will be deleted once JNI function will return

2023-06-10 16:15 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +    }
```suggestion
```
Revert this... `sk_CRYPTO_BUFFER_pop_free(stack, CRYPTO_BUFFER_free);` will free all elements.

2023-06-10 16:15 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +            (*e)->DeleteLocalRef(e, resultBytes);
This is not needed... will be released once the function returns. 
```suggestion
```

2023-06-10 16:15 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +        (*e)->DeleteLocalRef(e, resultBytes);
```suggestion
```

`JNI_ABORT` is correct... also local delete is not needed.

2023-06-11 05:27 UTC, wuhaocn commented
I added the code to remove local references again

1. Performed a performance test and found that there was no Memory leak when manual release was performed, and there would be Memory leak if manual release was not performed

2. The existence of local references will prevent garbage collection pointing to objects. If local references are used in the loop, it is recommended to manually release them

3. Could it be that the object control created by C was not handed over to Java, causing the context to be lost

2023-06-11 06:13 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +    }
@wuhaocn please address this ...

2023-06-11 06:28 UTC, normanmaurer requested changes

2023-06-11 06:28 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +        (*e)->ReleaseByteArrayElements(e, resultBytes, b, 0);
Why not JNI_ABORT ?

2023-06-11 06:28 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_quiche.c
> +    memcpy(token_buf, buf, buf_len);
Why do we need the extra memcpy here ? Shouldn't the original code be fine as long as we add the missing release ?

2023-06-11 06:28 UTC, normanmaurer commented on codec-native-quic/src/main/c/netty_quic_boringssl.c
> +        (*env)->ReleaseByteArrayElements(env, bytes, (jbyte*)data, 0);
Why not JNI_ABORT?

2023-06-11 07:59 UTC, wuhaocn commented
I modified it according to what you said. The previous code was modified with chatgbt. I gave it a memory overflow code snippet and pointed out which piece of memory leaked it to modify it.
Manual release is more reliable than automatic release. According to the stress test, there is no obvious memory overflow, and only a small amount of 32 bytes of memory has not been released.
Let me put the pressure on for a longer time to see, the modification of this request is a bit messy, I will make a new one or you can modify it directly if you see no problem

2023-06-11 07:59 UTC, closed without merging